---
name: order_taker
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.16.1 <3.0.0'
dependencies:
  cloud_firestore: ^3.1.13
  cupertino_icons: ^1.0.2
  device_preview: ^1.0.0
  firebase_auth: ^3.3.14
  firebase_core: ^1.14.1
  firebase_storage: ^10.2.16
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  google_fonts: ^2.3.1
  image_picker: ^0.8.5+3
  flutter_rating_bar: ^4.0.1
  readmore: ^2.1.0
  cached_network_image: ^3.2.1
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.2.5
  introduction_screen: ^3.0.1
dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/ikona.png
flutter_native_splash:
  android_12: true
  background_image: assets/Background2.png
  image: assets/eto.png
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
