---
name: order_taker
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.16.1 <3.0.0'
dependencies:
  cloud_firestore: ^4.1.0
  cupertino_icons: ^1.0.2
  device_preview: ^1.0.0
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  firebase_storage: ^11.0.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  google_fonts: ^3.0.1
  image_picker: ^0.8.5+3
  flutter_rating_bar: ^4.0.1
  readmore: ^2.1.0
  cached_network_image: ^3.2.1
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.5
  introduction_screen: ^3.1.6
  geocoding: ^2.0.5
  map_launcher: ^2.4.0
  flutter_svg: ^1.1.6
  url_launcher: ^6.1.7
dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
flutter_icons:
  android: launcher_icon
  ios: true
  adaptive_icon_background: "#ffffff"
  image_path: assets/logo_background.png
flutter_native_splash:
  color: "#ffffff"
  image: assets/logo_words.png
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
